### ISSUE TITLE
Tests fail for isoschematron extraction

### ISSUE THREAD

**Issue by peterstadler** [TEIC/oxgarage#14]
The tests for isoschematron extraction (see https://github.com/TEIC/oxgarage/blob/e52c313a9b41b2156cc3a71260e5efaa9088e61d/Tests/Makefile#L72 and https://github.com/TEIC/oxgarage/blob/e52c313a9b41b2156cc3a71260e5efaa9088e61d/Tests/Makefile#L74)  fail with the following error: 

```
Error on line 14 column 47 
  XTSE0165: I/O error reported by XML parser processing
  file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
net.sf.saxon.s9api.SaxonApiException: I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:742)
	at pl.psnc.dl.ege.MultiXslConverter.performStandardTransformation(MultiXslConverter.java:260)
	at pl.psnc.dl.ege.MultiXslConverter.convert(MultiXslConverter.java:100)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.sf.saxon.trans.XPathException: I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:455)
	at net.sf.saxon.event.Sender.send(Sender.java:138)
	at net.sf.saxon.style.StylesheetModule.loadStylesheetModule(StylesheetModule.java:129)
	at net.sf.saxon.style.UseWhenFilter.processIncludeImport(UseWhenFilter.java:274)
	at net.sf.saxon.style.UseWhenFilter.startElement(UseWhenFilter.java:210)
	at net.sf.saxon.event.StartTagBuffer.startContent(StartTagBuffer.java:235)
	at net.sf.saxon.event.ProxyReceiver.startContent(ProxyReceiver.java:174)
	at net.sf.saxon.event.ProxyReceiver.startContent(ProxyReceiver.java:174)
	at net.sf.saxon.event.ProxyReceiver.startContent(ProxyReceiver.java:174)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:375)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
	at net.sf.saxon.event.Sender.send(Sender.java:164)
	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:231)
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:106)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:739)
	... 5 more
Caused by: java.io.FileNotFoundException: /usr/local/common/functions.xsl (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
	... 29 more
22:13:59,725        ERROR ConversionPerformer:50 - I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
22:13:59,725        ERROR EGEImpl:341 - I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
pl.psnc.dl.ege.exception.ConverterException: I/O error reported by XML parser processing file:/usr/local/common/functions.xsl: /usr/local/common/functions.xsl (No such file or directory)
	at pl.psnc.dl.ege.MultiXslConverter.convert(MultiXslConverter.java:109)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)
```

Maybe OxGarage is expecting the Stylesheet `odds/extract-isosch.xsl` to be called from a `profile` dir (which results in the empty string, subsequently resulting in "" + $separator = root dir)?

**Comment by peterstadler** [comment]
just tested and works in both OxGarage and TEIGarage. Probably fixed in the Stylesheets?
