### ISSUE TITLE
Selfhosting of oxgarage not possible

### ISSUE THREAD

**Issue by jthomae1** [TEIC/oxgarage#16]
Hello,

I tried to setup an installation of oxgarage on an Ubuntu 16.04 system.

First I tried it with docker, using the teic docker image. I followed the installation guide from https://hub.docker.com/r/teic/oxgarage/.

![bildschirmfoto 2018-02-09 um 08 56 55](https://user-images.githubusercontent.com/8523176/36017254-3bdc9412-0d77-11e8-9857-5205a135342e.png)

Because something went wrong (see picture above), I tried the manual installation, using the installation guide of this github repo step by step. 

I run into the same error. In the tomcat log I found following error:

`08-Feb-2018 14:34:52.158 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ValidationServlet] in context with path [/ege-webservice] threw exception [Servlet execution threw an exception] with root cause
 java.lang.NoClassDefFoundError: Could not initialize class pl.psnc.dl.ege.tei.ConverterConfiguration
	at pl.psnc.dl.ege.tei.TEIConverter.getPossibleConversions(TEIConverter.java:1033)
	at pl.psnc.dl.ege.component.NamedConverter.getPossibleConversions(NamedConverter.java:51)
	at pl.psnc.dl.ege.EGEImpl.initialize(EGEImpl.java:127)
	at pl.psnc.dl.ege.EGEImpl.<init>(EGEImpl.java:109)
	at pl.psnc.dl.ege.webapp.servlet.ValidationServlet.printAvailableValidations(ValidationServlet.java:84)
	at pl.psnc.dl.ege.webapp.servlet.ValidationServlet.doGet(ValidationServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`

Any ideas what's wrong with my installation? Am I doing something wrong?

**Comment by jthomae1** [comment]
I am getting the same errors in chrome like the user in issue #1

**Comment by hcayless** [comment]
It's working for me (just tried it out for the first time). I'd make sure you're pulling and running the dev tag, because there isn't a latest, the way Peter has it set up currently. So `docker pull teic/oxgarage:dev` and then `docker run ... teic/oxgarage:dev`. I imagine that will change when we do a proper release. 

The error you're seeing tells me the ege-webclient is failing to talk to the ege-webservice. You can try requesting `http://localhost:8080/ege-webservice/`, which should give you a message proudly announcing that it's a RESTful service (while failing utterly to tell you what you can do from there, proving that it's not RESTful at all, (ლ‸－).  But I digress). If you get an error message, it may help tell you what's going wrong.

**Comment by jthomae1** [comment]
Thank you for the quick response, I tried the tag **RV-xslt3attempt** because it was the only one who was available at this time. I will try **dev** soon. 

There were no error messages at http://localhost:8080/ege-webservice/, only the RESTful message you expected.

**Comment by jthomae1** [comment]
I tried it with the tag teic/oxgarage:dev on a fresh Ubuntu 16.04. VM and the same error occurs.

The docker command I used:

`docker run --rm -p 8080:8080 -v /opt/stylesheets:/usr/share/xml/tei/stylesheet -v /opt/stylesheets/tei-3.3.0/xml/tei/odd:/usr/share/xml/tei/odd -e WEBSERVICE_URL=http://localhost:8080/ege-webservice/ --name oxgarage teic/oxgarage:dev`

Is there something with the stylesheets not correct? I downloaded the stylesheets from https://sourceforge.net/projects/tei/files/Stylesheets/ and copied them (tei-xsl-7.44.0 and tei-3.3.0) to /opt/stylesheets/ 

I also tried -v /opt/stylesheets/tei-xsl-7.44.0:/usr/share/xml/tei/stylesheet in the docker command.

**Comment by peterstadler** [comment]
Whenever I got this error it was due to an issue with the Stylesheets or Guidelines paths. So, please make sure that the Stylesheets path you are using holds the `profiles` directory and the Guidelines path the `p5subset.xml` file.
Another caveat (especially for Mac users) is that there must not be any extra files/folders (e.g. `.DS_Store`) in those directories or OxGarage will choke on these.

**Comment by jthomae1** [comment]
> make sure that the Stylesheets path you are using holds the profiles directory

That fixed it for me! I would recommend that you add this hint to the installation guides on github and dockerhub like you done it for the P5 sources path. Thank's for your fast support!
