### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by mhsdeveloper** [TEIC/oxgarage#19]
The documentation references that the P5 source folder that contains p5subset.xml needs to go in /usr/share/xml/tei/odd  But the tei release doesn't have this file. Can the docs please be updated to reflect current releases? I am unable to get oxgarage to run properly, with this error:

<error msg="Could not initialize class pl.psnc.dl.ege.tei.ConverterConfiguration" exclass="class java.lang.NoClassDefFoundError" >java
.lang.NoClassDefFoundError: Could not initialize class pl.psnc.dl.ege.tei.ConverterConfiguration
	at pl.psnc.dl.ege.tei.TEIConverter.getPossibleConversions(TEIConverter.java:1033)
	at pl.psnc.dl.ege.component.NamedConverter.getPossibleConversions(NamedConverter.java:51)
	at pl.psnc.dl.ege.EGEImpl.initialize(EGEImpl.java:127)
	at pl.psnc.dl.ege.EGEImpl.<init>(EGEImpl.java:109)
	at pl.psnc.dl.ege.webapp.servlet.ConversionServlet.performConversion(ConversionServlet.java:291)
	at pl.psnc.dl.ege.webapp.servlet.ConversionServlet.doPost(ConversionServlet.java:268)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
</error>

Thanks for any help

**Comment by peterstadler** [comment]
If you download the current `tei-3.3.0.zip` from the [TEI releases page](https://github.com/TEIC/TEI/releases/download/P5_Release_3.3.0/tei-3.3.0.zip) you should find the file `p5subset.xml` (after extracting the archive) under `tei-3.3.0/xml/tei/odd`.
That folder needs to be mounted as `/usr/share/xml/tei/odd` into the docker container.

I just freshly downloaded the release archive and can confirm that the file exists: 
```bash
unzip -l tei-3.3.0.zip | grep p5subset.xml   
```

returns

```bash
  3829546  01-31-2018 14:17   xml/tei/odd/p5subset.xml
```

Can you tell us a bit more about what you were trying to do?

**Comment by mhsdeveloper** [comment]
Thanks; I had downloaded the source code from that page, and not the release zip.


After starting over and double checked the location of TEI and xsl AND restarting tomcat, it works!


The Oxgarage documentation does say to download the TEI source, so maybe it might make sense to reword that to read "download the main release zip file" or something like that. Also, since I don't use docker,  I was lost for I while until I read the "using docker" section and noted the links to the TEI source. Might be helpful to put a small note in the "without docker" section.


Thanks so much!


________________________________

**Comment by martindholmes** [comment]
If you're on Linux, I think that installing the deb packages would put the p5subset.xml file in the required place, wouldn't it?

**Comment by mhsdeveloper** [comment]
I think on Debian (Ubuntu, LinuxMint etc) it would; we're on Centos (redhat, fedora using rpm's) and wasn't clear to me how to unpack .deb files. But it did work as described, just needed to understand the instructions a little clearer.


I'm working Oxgarage into a series of processes to convert word files of historical letters to TEI, for some folks who are not too handy with XML. So running Oxgarage on our server will allow me to stream line the whole conversion to (hopefully) a single drag and drop.


thanks again.

________________________________
