### ISSUE TITLE
Converting odt to tei resulting in javax.xml.transform.TransformerException: Can't transform a Source of type net.sf.saxon.tree.tiny.TinyDocumentImpl

### ISSUE THREAD

**Issue by Possommi** [TEIC/oxgarage#26]
When I try to convert the attached odt file I am getting the following exception.

INFO TEIConverter:148 - 2018/07/18 14:01:27: Converting FROM:  Documents:OpenOffice Text (.odt):odt,application/vnd.oasis.opendocument.text TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile null
14:01:27,451        DEBUG TEIConverter:241 - Profile not found, setting default profile...
javax.xml.transform.TransformerException: Can't transform a Source of type net.sf.saxon.tree.tiny.TinyDocumentImpl
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:418)
	at org.tei.utils.XMLUtils.getXMLNodeAsString(XMLUtils.java:195)
	at org.tei.utils.XMLUtils.storeDocument(XMLUtils.java:52)
	at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:206)
	at pl.psnc.dl.ege.tei.TEIConverter.transformFromOdt(TEIConverter.java:842)
	at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:244)
	at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:153)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)

I attached the odt document (remove .txt file extension)
[test_doc.odt.txt](https://github.com/TEIC/oxgarage/files/2205699/test_doc.odt.txt)

**Comment by peterstadler** [comment]
I just tested with http://oxgarage.tei-c.org/ and http://oxgarage2.tei-c.org/ and both provided me with a proper TEI file. Can you provide more information how you're running OxGarage? Are you using one of the servers above? Are you running your own? with docker?

**Comment by Possommi** [comment]
I setup the webservice on an ubuntu (Ubuntu 16.04.4 LTS) machine with Tomcat 8.5.23. I placed the property file at /etc/oxgarage.properties. All stylesheets are located at /usr/share/xml/tei. LibreOffice is also installed, but not used/necessary for the transformation. I could see the temporary file is created at /var/cache/oxgarage/temp/<uuid>

**Comment by peterstadler** [comment]
I believe this to be an issue with Tomcat8. When I switch to Tomcat8 (by changing https://github.com/TEIC/oxgarage/blob/9dd2f21f4c699c3955d7ff19f9585938762f0c75/Dockerfile#L39) I get a similar error:

```
10:34:42,719         INFO ManifestParser:108 - got SAX parser factory - org.apache.xerces.jaxp.SAXParserFactoryImpl@133b8199
10:34:42,722         INFO PluginRegistryImpl:109 - configured, stopOnError=false, isValidating=true
10:34:45,172         INFO PluginRegistryImpl:268 - plug-in and fragment descriptors registered - 5
10:34:45,176         INFO StandardPluginManager:421 - plug-in started - pl.psnc.dl.ege.root@1.0.0
10:34:45,176         INFO StandardPluginManager:421 - plug-in started - oo-converter@1.0.0
10:34:45,185         INFO StandardPluginManager:421 - plug-in started - tei-converter@1.0.0
10:34:47,628         INFO StandardPluginManager:421 - plug-in started - pl.psnc.dl.ege.xsl.converter@1.0.0
10:34:47,662         INFO StandardPluginManager:421 - plug-in started - pl.psnc.dlteam.ege.validator@1.0.0
10:35:55,348         INFO TEIConverter:149 - 2018/07/27 10:35:55: Converting FROM:  Documents:OpenOffice Text (.odt):odt,application/vnd.oasis.opendocument.text TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile default
Exception in thread "Thread-8" java.lang.NoSuchMethodError: net.sf.saxon.Configuration.setProcessor(Ljava/lang/Object;)V
	at net.sf.saxon.s9api.Processor.<init>(Processor.java:73)
	at org.tei.utils.SaxonProcFactory.getProcessor(SaxonProcFactory.java:21)
	at pl.psnc.dl.ege.tei.ComplexConverter.getTEI(ComplexConverter.java:245)
	at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:204)
	at pl.psnc.dl.ege.tei.TEIConverter.transformFromOdt(TEIConverter.java:877)
	at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:245)
	at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:154)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.lang.Thread.run(Thread.java:748)
```

Could you try with sticking with Tomcat7 (or use the Dockerfile provided at https://hub.docker.com/r/teic/oxgarage/)

Lastly, if you're able to fix this issue, a PR is highly appreciated :)

**Comment by Possommi** [comment]
It is indeed an issue with tomcat 8.
