### ISSUE TITLE
Conversion fail "Error: class pl.psnc.dl.ege.exception.ConverterException" with war and Tomacat9

### ISSUE THREAD

**Issue by liladude** [TEIC/oxgarage#38]
Hello,
I just installed OxGarage on our Debian server running Tomcat by uploading the needed war(s), changing the files as per instruction and uploading the /usr/share/xml/tei needed files.
I installed libreoffice-common and pointed the openoffice to it (openoffice is no longer available on Debian 8 as standard package)
My tomcat run on a different port, but everything seems to work nice, until I try to convert a file. 
I have the very same error displayed in other issues "Error: class pl.psnc.dl.ege.exception.ConverterException - null" or creates an empty file (i.e. if I convert to tex), but those examples were running on Docker, so I am stuck. 
Can anybody help me debug?
Regards,
Lila

**Comment by peterstadler** [comment]
Some thoughts to help you debug:

* I was having trouble with more recent Tomcats as well, so we stick with tomcat7 for the Docker image
* the file paths of the TEI stylesheets and sources can be confusing. If you're running Debian, you might want to try our Debian packages which will install everything in the right place. Instructions are at https://packages.tei-c.org/deb/
* there should be more detailed error messages in the Tomcat logs which might give you a hint

**Comment by liladude** [comment]
Thank you, I will sort this from the logs, when I find them X_X
Do you know if I need all of the tei packages installed? because the seems to be like 800 mb.
I will try to debug the problems one by one and report, else I will install tomcat7 and restart!

**Comment by peterstadler** [comment]
> Do you know if I need all of the tei packages installed? because the seems to be like 800 mb.

I think you'll need at least tei-xsl and tei-p5-source.

**Comment by liladude** [comment]
Thank you, I just realized it was already 800 MB even the downloaded version I had manually put on, so I went ahed, but nothing changed.
This is the error in catalina.out 
`
10:45:49,514        ERROR ConversionPerformer:50 -
10:45:49,515        ERROR EGEImpl:341 -
pl.psnc.dl.ege.exception.ConverterException
        at uk.ac.ox.oucs.oxgarage.oo.OOConverter.convert(OOConverter.java:85)
        at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
        at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
        at java.lang.Thread.run(Thread.java:748)
`
I see the file upload dir in temp... If you can spot a problem, else I will restart with Tomcat7
Thank you again!

**Comment by peterstadler** [comment]
Regarding OpenOffice: it's ok to install LibreOffice (our OxGarage Docker image comes with LibreOffice as well), but you might need to add a symlink like `ln -s /usr/lib/libreoffice /usr/lib/openoffice`.

Regarding log4j: try to copy the file log4j.xml from the OxGarage root to `/var/cache/oxgarage/log4j.xml`.

(The information given above is what I read from our own [Dockerfile](https://github.com/TEIC/oxgarage/blob/dev/Dockerfile), which might give you further hints)

**Comment by liladude** [comment]
Thank you for your answer!
I had copied the log4j.xml from the git and put in /var/cache/oxgarage as per tutorial, but it seems that there is a problem. Since it appeared with Tomcat7 too, I was looking to [this thread](https://stackoverflow.com/questions/12532339/no-appenders-could-be-found-for-loggerlog4j) but I need to understand if I can do the suggested modifications.
I have added the simlink (but I also edited all references to point them to libreoffice). The reference to OfficeHome seems to have disappeared from the logs, no the error is 
`Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException
could not load document: input.odt` 
I will search further!

**Comment by liladude** [comment]
Ok, upon further search it seems that jodconverter needs port 2002 opened, I will have to wait for a manager that can open it for me since I seem unable to finde where the port is set. 
Also, no files are written in /var/cache/oxgarage/temp when uploading. I can find directories under buff, but nothing in them.

**Comment by peterstadler** [comment]
any updates on this? Otherwise I'd like to close the issue …

**Comment by peterstadler** [comment]
closing due to inactivity – please feel free to reopen if the error still occurs.
