### ISSUE TITLE
xHTML conversion fails "Error: class pl.psnc.dl.ege.exception.ConverterException" on OxGarage

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/oxgarage#40]
Got an error message trying to convert to EPUB an HTML file that seemed correct XML.

**Comment by peterstadler** [comment]
I can confirm the issue. The error message is

```
Caused by: java.io.FileNotFoundException: /usr/share/xml/tei/stylesheet/css/epub-print.css (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
at net.sf.saxon.lib.StandardUnparsedTextResolver.resolve(StandardUnparsedTextResolver.java:82)
... 23 more
```

It is related to #9 and probably be solved by https://github.com/TEIC/Stylesheets/pull/394

**Comment by peterstadler** [comment]
Should be fixed in the OxGarage successor https://github.com/TEIC/teigarage (see https://github.com/TEIC/TEIGarage/issues/18). If the issue reappears, please file a ticket there

NB, the deployment at teigarage.tei-c.org is not yet updated but will be in the next days
