### ISSUE TITLE
EGEConfigurationManager:509 -  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Possommi** [TEIC/oxgarage#43]
when invoking http://127.0.0.1:8080/ege-webclient/ I get the following exception below. I am using tomcat 8.5.39 on macOS catalina.

It is probably a configuration issue but I do not know where to start. I have placed the property file here /etc/oxgarage.properties and adopted the pathes to the actual locations of the stylesheets.

Any suggestions?

Exception:
========
EGEConfigurationManager:509 - 
java.lang.NullPointerException
	at pl.psnc.dl.ege.configuration.EGEConfigurationManager.searchForData(EGEConfigurationManager.java:500)
	at pl.psnc.dl.ege.configuration.EGEConfigurationManager.getXslExtensions(EGEConfigurationManager.java:419)
	at pl.psnc.dl.ege.configuration.EGEConfigurationManager.getAllComponents(EGEConfigurationManager.java:370)
	at pl.psnc.dl.ege.configuration.EGEConfigurationManager.getAvailableConverters(EGEConfigurationManager.java:253)
	at pl.psnc.dl.ege.EGEImpl.initialize(EGEImpl.java:120)
	at pl.psnc.dl.ege.EGEImpl.<init>(EGEImpl.java:109)
	at pl.psnc.dl.ege.webapp.servlet.ConversionServlet.performConversion(ConversionServlet.java:291)
	at pl.psnc.dl.ege.webapp.servlet.ConversionServlet.doPost(ConversionServlet.java:268)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by Possommi** [comment]
Problem was that the configuration located at /etc/oxgarage.properties was not loaded. One has to alter the configuration directly in /tomcat/webapps/ege-webservice/WEB-INF/lib/oxgarage.properties

**Comment by Possommi** [comment]
But there is another error now when I try to convert an OpenOffice document: 

INFO TEIConverter:149 - 2020/02/07 13:14:56: Converting FROM:  Documents:OpenOffice Text (.odt):odt,application/vnd.oasis.opendocument.text TO Documents:TEI P5 XML Document:TEI,text/xml WITH profile null
Exception in thread "Thread-15" java.lang.NoSuchMethodError: 'void net.sf.saxon.Configuration.setProcessor(java.lang.Object)'
	at net.sf.saxon.s9api.Processor.<init>(Processor.java:73)
	at org.tei.utils.SaxonProcFactory.getProcessor(SaxonProcFactory.java:21)
	at pl.psnc.dl.ege.tei.ComplexConverter.getTEI(ComplexConverter.java:245)
	at pl.psnc.dl.ege.tei.ComplexConverter.toTEI(ComplexConverter.java:204)
	at pl.psnc.dl.ege.tei.TEIConverter.transformFromOdt(TEIConverter.java:877)
	at pl.psnc.dl.ege.tei.TEIConverter.convertDocument(TEIConverter.java:245)
	at pl.psnc.dl.ege.tei.TEIConverter.convert(TEIConverter.java:154)
	at pl.psnc.dl.ege.component.NamedConverter.convert(NamedConverter.java:44)
	at pl.psnc.dl.ege.ConversionPerformer.run(ConversionPerformer.java:45)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by peterstadler** [comment]
Hi, I really recommend using Docker for these things because all the dependencies are properly resolved in the image at https://hub.docker.com/r/teic/oxgarage/

That said, you'll probably need to have OpenOffice installed and the path right? From https://github.com/TEIC/oxgarage#running-the-application-packages : 
> Note also that OxGarage needs a headless OpenOffice available to do some of its work. The properties file specifies that this is at /usr/lib/openoffice/, but this can be changed if needed

**Comment by Possommi** [comment]
Thank you for your response. I have done all the mentioned configuration. The problem is stated in the following line "java.lang.NoSuchMethodError: 'void net.sf.saxon.Configuration.setProcessor". And if you look in the API you really see that there is no such method in https://www.saxonica.com/documentation9.8/#!javadoc/net.sf.saxon.s9api/Processor (Saxon-HE-9.8.0-7.jar). This is probably some sort of a dependency problem.

**Comment by Possommi** [comment]
using branch origin/minor-saxon-upgrade fixes the issue

**Comment by peterstadler** [comment]
Good to hear! We should really merge that PR, what do you think @hcayless ?

**Comment by peterstadler** [comment]
> Thank you for your response. I have done all the mentioned configuration. The problem is stated in the following line "java.lang.NoSuchMethodError: 'void net.sf.saxon.Configuration.setProcessor". And if you look in the API you really see that there is no such method in https://www.saxonica.com/documentation9.8/#!javadoc/net.sf.saxon.s9api/Processor (Saxon-HE-9.8.0-7.jar). This is probably some sort of a dependency problem.

The setProcessor issue sounds familiar, see https://github.com/peterstadler/oxgarage-docker/issues/2#issuecomment-358663386 

Anyway, I'm closing the issue now due to inactivity and since a workaround seems to be found. Please feel free to reopen if I'm wrong about this!
